packages:
  - packages/*

overrides:
  '@eslint-community/eslint-utils': ^4.7.0
  '@typescript-eslint/utils': ^8.32.0
  eslint: ^9.26.0
  tsx: ^4.19.4

catalogs:
  dev:
    '@eslint/config-inspector': ^1.0.2
    '@types/node': ^22.15.17
    bumpp: ^10.1.0
    eslint-typegen: ^2.1.0
    execa: ^9.5.3
    fast-glob: ^3.3.3
    lint-staged: ^15.5.2
    sass: ^1.87.0
    simple-git-hooks: ^2.13.0
    svelte: ^5.28.2
    tsup: ^8.4.0
    tsx: ^4.19.4
    typescript: ^5.8.3
    vitest: ^3.1.3
  peer:
    '@eslint-react/eslint-plugin': ^1.49.0
    '@prettier/plugin-xml': ^3.4.1
    '@unocss/eslint-plugin': ^66.1.1
    astro-eslint-parser: ^1.2.2
    eslint: ^9.26.0
    eslint-plugin-astro: ^1.3.1
    eslint-plugin-format: ^1.0.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    eslint-plugin-solid: ^0.14.5
    eslint-plugin-svelte: ^3.5.1
    eslint-plugin-tailwindcss: ^3.18.0
    eslint-plugin-vue: ^10.1.0
    eslint-plugin-vuejs-accessibility: ^2.4.1
    eslint-processor-vue-blocks: ^2.0.0
    prettier: ^3.5.3
    prettier-plugin-astro: ^0.14.1
    prettier-plugin-slidev: ^1.0.5
    stylelint: ^16.19.1
    svelte-eslint-parser: ^1.1.3
    vue-eslint-parser: ^10.1.3
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
    '@eslint/markdown': ^6.4.0
    '@pengzhanbo/utils': ^2.1.0
    '@stylelint-types/stylelint-order': ^7.0.0
    '@stylelint-types/stylelint-scss': ^6.11.0
    '@stylelint-types/stylelint-stylistic': ^3.1.3
    '@stylistic/eslint-plugin': ^4.2.0
    '@stylistic/stylelint-plugin': ^3.1.2
    '@typescript-eslint/eslint-plugin': ^8.32.0
    '@typescript-eslint/parser': ^8.32.0
    '@vitest/eslint-plugin': ^1.1.44
    eslint-config-flat-gitignore: ^2.1.0
    eslint-flat-config-utils: ^2.0.1
    eslint-merge-processors: ^2.0.0
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-command: ^3.2.0
    eslint-plugin-import-x: ^4.11.1
    eslint-plugin-jsdoc: ^50.6.11
    eslint-plugin-jsonc: ^2.20.0
    eslint-plugin-n: ^17.18.0
    eslint-plugin-no-only-tests: ^3.3.0
    eslint-plugin-perfectionist: ^4.12.3
    eslint-plugin-pnpm: ^0.3.1
    eslint-plugin-regexp: ^2.7.0
    eslint-plugin-toml: ^0.12.0
    eslint-plugin-unicorn: ^59.0.1
    eslint-plugin-unused-imports: ^4.1.4
    eslint-plugin-yml: ^1.18.0
    globals: ^16.1.0
    jsonc-eslint-parser: ^2.4.0
    local-pkg: ^1.1.1
    parse-gitignore: ^2.0.0
    postcss: ^8.5.3
    postcss-html: ^1.8.0
    stylelint-config-html: ^1.1.0
    stylelint-config-standard: ^38.0.0
    stylelint-config-standard-scss: ^14.0.0
    stylelint-define-config: ^16.19.0
    stylelint-order: ^7.0.0
    toml-eslint-parser: ^0.10.0
    yaml-eslint-parser: ^1.3.0

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
