packages:
  - packages/*

overrides:
  '@eslint-community/eslint-utils': ^4.7.0
  '@typescript-eslint/utils': ^8.39.1
  eslint: ^9.33.0
  tsx: ^4.20.4

catalogs:
  dev:
    '@eslint/config-inspector': ^1.1.0
    '@types/eslint-plugin-jsx-a11y': ^6.10.0
    '@types/node': ^24.2.1
    bumpp: ^10.2.3
    eslint-typegen: ^2.3.0
    execa: ^9.6.0
    fast-glob: ^3.3.3
    lint-staged: ^16.1.5
    sass: ^1.90.0
    simple-git-hooks: ^2.13.1
    svelte: ^5.38.1
    tsdown: ^0.14.1
    tsx: ^4.20.4
    typescript: ^5.9.2
    vitest: ^3.2.4
  peer:
    '@eslint-react/eslint-plugin': ^1.52.3
    '@next/eslint-plugin-next': ^15.4.0-canary.115
    '@prettier/plugin-xml': ^3.4.2
    '@unocss/eslint-plugin': ^66.4.2
    astro-eslint-parser: ^1.2.2
    eslint: ^9.33.0
    eslint-plugin-astro: ^1.3.1
    eslint-plugin-format: ^1.0.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    eslint-plugin-solid: ^0.14.5
    eslint-plugin-svelte: ^3.11.0
    eslint-plugin-tailwindcss: ^3.18.2
    eslint-plugin-vue: ^10.4.0
    eslint-plugin-vuejs-accessibility: ^2.4.1
    eslint-processor-vue-blocks: ^2.0.0
    prettier: ^3.6.2
    prettier-plugin-astro: ^0.14.1
    prettier-plugin-slidev: ^1.0.5
    stylelint: ^16.23.1
    svelte-eslint-parser: ^1.3.1
    vue-eslint-parser: ^10.2.0
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
    '@eslint/markdown': ^7.1.0
    '@pengzhanbo/utils': ^2.1.0
    '@stylelint-types/stylelint-order': ^7.0.0
    '@stylelint-types/stylelint-scss': ^6.11.0
    '@stylelint-types/stylelint-stylistic': ^3.1.3
    '@stylistic/eslint-plugin': ^5.2.3
    '@stylistic/stylelint-plugin': ^4.0.0
    '@typescript-eslint/eslint-plugin': ^8.39.1
    '@typescript-eslint/parser': ^8.39.1
    '@vitest/eslint-plugin': ^1.3.4
    eslint-config-flat-gitignore: ^2.1.0
    eslint-flat-config-utils: ^2.1.1
    eslint-merge-processors: ^2.0.0
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-command: ^3.3.1
    eslint-plugin-import-lite: ^0.3.0
    eslint-plugin-jsdoc: ^53.0.1
    eslint-plugin-jsonc: ^2.20.1
    eslint-plugin-jsx-a11y: ^6.10.2
    eslint-plugin-n: ^17.21.3
    eslint-plugin-no-only-tests: ^3.3.0
    eslint-plugin-perfectionist: ^4.15.0
    eslint-plugin-pnpm: ^1.1.0
    eslint-plugin-regexp: ^2.10.0
    eslint-plugin-toml: ^0.12.0
    eslint-plugin-unicorn: ^60.0.0
    eslint-plugin-unused-imports: ^4.1.4
    eslint-plugin-yml: ^1.18.0
    globals: ^16.3.0
    jsonc-eslint-parser: ^2.4.0
    local-pkg: ^1.1.1
    parse-gitignore: ^2.0.0
    postcss: ^8.5.6
    postcss-html: ^1.8.0
    stylelint-config-html: ^1.1.0
    stylelint-config-standard: ^39.0.0
    stylelint-config-standard-scss: ^15.0.1
    stylelint-define-config: ^16.22.0
    stylelint-order: ^7.0.0
    toml-eslint-parser: ^0.10.0
    yaml-eslint-parser: ^1.3.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - simple-git-hooks
  - unrs-resolver
