declare module 'eslint-plugin-tailwindcss'
declare module 'eslint-plugin-react'
declare module 'eslint-plugin-react-hooks'
declare module 'eslint-plugin-react-refresh'
declare module '@next/eslint-plugin-next'
