import type { OxlintConfig } from 'oxlint'

export const defaultIgnorePatterns: string[] = [
  '**/logs',
  '**/*.log',
  '**/npm-debug.log*',
  '**/yarn-debug.log*',
  '**/yarn-error.log*',
  '**/pids',
  '**/*.pid',
  '**/*.seed',
  '**/*.pid.lock',
  '**/lib-cov',
  '**/coverage',
  '**/.nyc_output',
  '**/.grunt',
  '**/bower_components',
  '**/.lock-wscript',
  '**/node_modules/',
  '**/jspm_packages/',
  '**/typings/',
  '**/.npm',
  '**/.eslintcache',
  '**/.node_repl_history',
  '**/*.tgz',
  '**/.yarn-integrity',
  '**/.env',
  '**/.cache',
  '**/.next',
  '**/.nuxt',
  '**/dist',
  '**/.serverless',
  '**/.idea',
  '**/*.lerna_backup',
  '**/_fixtures',
  '**/.temp',
  '**/.history',
  '**/.trae',
  '**/.claude',
  '**/node_modules',
  '**/package-lock.json',
  '**/yarn.lock',
  '**/pnpm-lock.yaml',
  '**/bun.lockb',
  '**/output',
  '**/temp',
  '**/tmp',
  '**/.tmp',
  '**/.vuepress/.cache',
  '**/.vuepress/.temp',
  '**/.vitepress/cache',
  '**/.svelte-kit',
  '**/.vercel',
  '**/.changeset',
  '**/.output',
  '**/.vite-inspect',
  '**/.yarn',
  '**/CHANGELOG*.md',
  '**/LICENSE*',
  '**/__snapshots__',
  '**/vite.config.*.timestamp-*',
  '**/auto-import?(s).d.ts',
  '**/components.d.ts',
  '**/.context',
  '**/.agents',
  '**/.*/skills',
]

export function ignore(ignorePatterns?: string[]): OxlintConfig {
  return {
    ignorePatterns: [...defaultIgnorePatterns, ...(ignorePatterns || [])],
  }
}
