import type { DummyRuleMap, OxlintConfig } from 'oxlint'

interface TestOptions {
  rules?: DummyRuleMap
}

export function test({ rules }: TestOptions = {}): OxlintConfig {
  return {
    overrides: [
      {
        plugins: ['eslint', 'vitest', 'typescript', 'unicorn'],
        files: [
          '**/__tests__/**/*.{js,ts,jsx,tsx,cjs,mjs,cts,mts}',
          '**/*.{spec,test,bench,benchmark}.{js,ts,jsx,tsx,cjs,mjs,cts,mts}',
        ],
        rules: {
          'id-length': 'off',
          'max-classes-per-file': 'off',
          'max-lines-per-function': 'off',
          'max-lines': 'off',
          'max-statements': 'off',
          'no-empty-function': 'off',
          'no-undefined': 'off',
          'no-underscore-dangle': 'off',
          'no-unused-expressions': 'off',

          'unicorn/consistent-function-scoping': 'off',
          'unicorn/no-thenable': 'off',

          'typescript/no-unnecessary-condition': 'off',
          'typescript/no-unsafe-member-access': 'off',
          'typescript/ban-ts-comment': 'off',
          'typescript/require-await': 'off',
          'typescript/explicit-function-return-type': 'off',
          'typescript/no-unsafe-argument': 'off',

          'vitest/consistent-test-it': ['error', { fn: 'it', withinDescribe: 'it' }],
          'vitest/no-identical-title': 'error',
          'vitest/no-import-node-test': 'error',
          'vitest/prefer-hooks-in-order': 'error',
          'vitest/prefer-lowercase-title': 'error',

          'vitest/consistent-each-for': 'off',
          'vitest/consistent-test-filename': 'off',
          'vitest/consistent-vitest-vi': 'off',
          'vitest/expect-expect': 'error',
          'vitest/hoisted-apis-on-top': 'off',
          'vitest/max-expects': 'off',
          'vitest/max-nested-describe': 'off',
          'vitest/no-alias-methods': 'off',
          'vitest/no-commented-out-tests': 'off',
          'vitest/no-conditional-expect': 'off',
          'vitest/no-conditional-in-test': 'off',
          'vitest/no-conditional-tests': 'off',
          'vitest/no-disabled-tests': 'off',
          'vitest/no-duplicate-hooks': 'off',
          'vitest/no-focused-tests': 'off',
          'vitest/no-hooks': 'off',
          'vitest/no-importing-vitest-globals': 'off',
          'vitest/no-interpolation-in-snapshots': 'off',
          'vitest/no-large-snapshots': 'off',
          'vitest/no-mocks-import': 'off',
          'vitest/no-restricted-matchers': 'off',
          'vitest/no-restricted-vi-methods': 'off',
          'vitest/no-standalone-expect': 'off',
          'vitest/no-test-prefixes': 'off',
          'vitest/no-test-return-statement': 'off',
          'vitest/no-unneeded-async-expect-function': 'off',
          'vitest/padding-around-after-all-blocks': 'off',
          'vitest/padding-around-test-blocks': 'off',
          'vitest/prefer-called-exactly-once-with': 'off',
          'vitest/prefer-called-once': 'off',
          'vitest/prefer-called-times': 'off',
          'vitest/prefer-called-with': 'off',
          'vitest/prefer-comparison-matcher': 'off',
          'vitest/prefer-describe-function-title': 'off',
          'vitest/prefer-each': 'off',
          'vitest/prefer-equality-matcher': 'off',
          'vitest/prefer-expect-assertions': 'off',
          'vitest/prefer-expect-resolves': 'off',
          'vitest/prefer-expect-type-of': 'off',
          'vitest/prefer-hooks-on-top': 'off',
          'vitest/prefer-import-in-mock': 'off',
          'vitest/prefer-importing-vitest-globals': 'off',
          'vitest/prefer-mock-promise-shorthand': 'off',
          'vitest/prefer-mock-return-shorthand': 'off',
          'vitest/prefer-snapshot-hint': 'off',
          'vitest/prefer-spy-on': 'off',
          'vitest/prefer-strict-boolean-matchers': 'off',
          'vitest/prefer-strict-equal': 'off',
          'vitest/prefer-to-be': 'off',
          'vitest/prefer-to-be-falsy': 'off',
          'vitest/prefer-to-be-object': 'off',
          'vitest/prefer-to-be-truthy': 'off',
          'vitest/prefer-to-contain': 'off',
          'vitest/prefer-to-have-been-called-times': 'off',
          'vitest/prefer-to-have-length': 'off',
          'vitest/prefer-todo': 'off',
          'vitest/require-awaited-expect-poll': 'off',
          'vitest/require-hook': 'off',
          'vitest/require-local-test-context-for-concurrent-snapshots': 'off',
          'vitest/require-mock-type-parameters': 'off',
          'vitest/require-test-timeout': 'off',
          'vitest/require-to-throw-message': 'off',
          'vitest/require-top-level-describe': 'off',
          'vitest/valid-describe-callback': 'off',
          'vitest/valid-expect': 'off',
          'vitest/valid-expect-in-promise': 'off',
          'vitest/valid-title': 'off',
          'vitest/warn-todo': 'off',
          ...rules,
        },
      },
    ],
  }
}
