import type { OxlintConfig } from 'oxlint'

export function typescript(): OxlintConfig {
  return {
    overrides: [
      {
        plugins: ['typescript'],
        files: ['**/*.?([cm])ts?(x)', '**/*.vue'],
        rules: {
          'constructor-super': 'off',
          'getter-return': 'off',
          'no-class-assign': 'off',
          'no-const-assign': 'off',
          'no-dupe-keys': 'off',
          'no-func-assign': 'off',
          'no-import-assign': 'off',
          'no-new-native-nonconstructor': 'off',
          'no-obj-calls': 'off',
          'no-redeclare': ['error', { builtinGlobals: false }],
          'no-setter-return': 'off',
          'no-this-before-super': 'off',
          'no-unreachable': 'off',
          'no-unsafe-negation': 'off',
          'no-with': 'off',
          'prefer-const': [
            'error',
            {
              destructuring: 'all',
              ignoreReadBeforeAssign: true,
            },
          ],
          'no-unused-expressions': [
            'error',
            {
              allowShortCircuit: true,
              allowTaggedTemplates: true,
              allowTernary: true,
            },
          ],
          'no-unused-vars': 'off',
          'no-useless-constructor': 'off',
          'no-use-before-define': [
            'error',
            {
              classes: false,
              functions: false,
              variables: true,
            },
          ],
          'typescript/ban-ts-comment': [
            'error',
            {
              'ts-expect-error': 'allow-with-description',
            },
          ],
          'typescript/no-duplicate-enum-values': 'error',
          'typescript/no-dynamic-delete': 'off',
          'typescript/no-empty-object-type': ['error', { allowInterfaces: 'always' }],
          'typescript/no-explicit-any': 'off',
          'typescript/no-extra-non-null-assertion': 'error',
          'typescript/no-extraneous-class': 'off',
          'typescript/no-invalid-void-type': 'off',
          'typescript/no-misused-new': 'error',
          'typescript/no-namespace': 'error',
          'typescript/no-non-null-asserted-nullish-coalescing': 'error',
          'typescript/no-non-null-asserted-optional-chain': 'error',
          'typescript/no-non-null-assertion': 'off',
          'typescript/no-require-imports': 'error',
          'typescript/no-this-alias': 'error',
          'typescript/no-unnecessary-type-constraint': 'error',
          'typescript/no-unsafe-declaration-merging': 'error',
          'typescript/no-unsafe-function-type': 'error',
          'typescript/no-wrapper-object-types': 'error',
          'typescript/prefer-as-const': 'error',
          'typescript/prefer-literal-enum-member': 'error',
          'typescript/prefer-namespace-keyword': 'error',
          'typescript/triple-slash-reference': 'off',
          'typescript/unified-signatures': 'off',
          'typescript/consistent-type-definitions': ['error', 'interface'],
          'typescript/consistent-type-imports': [
            'error',
            {
              disallowTypeAnnotations: false,
              fixStyle: 'separate-type-imports',
              prefer: 'type-imports',
            },
          ],
          'typescript/method-signature-style': ['error', 'property'],
          'typescript/no-import-type-side-effects': 'error',
          'typescript/dot-notation': ['error', { allowKeywords: true }],
        },
      },
      {
        plugins: ['typescript'],
        files: ['**/*.?([cm])ts', '**/*.?([cm])tsx'],
        rules: {
          'no-implied-eval': 'off',
          'typescript/await-thenable': 'error',
          'typescript/no-floating-promises': 'error',
          'typescript/no-for-in-array': 'error',
          'typescript/no-implied-eval': 'error',
          'typescript/no-misused-promises': 'error',
          'typescript/no-unnecessary-type-assertion': 'error',
          'typescript/no-unsafe-argument': 'error',
          'typescript/no-unsafe-assignment': 'error',
          'typescript/no-unsafe-call': 'error',
          'typescript/no-unsafe-member-access': 'error',
          'typescript/no-unsafe-return': 'error',
          'typescript/promise-function-async': 'error',
          'typescript/restrict-plus-operands': 'error',
          'typescript/restrict-template-expressions': 'error',
          'typescript/return-await': ['error', 'in-try-catch'],
          'typescript/strict-boolean-expressions': [
            'error',
            {
              allowNullableBoolean: true,
              allowNullableObject: true,
            },
          ],
          'typescript/switch-exhaustiveness-check': 'error',
          'typescript/unbound-method': 'error',
        },
      },
    ],
  }
}
