import type { DummyRuleMap, OxlintConfig } from 'oxlint'
import { defineRules } from '../utils'

interface UnicornOptions {
  rules?: DummyRuleMap
}

const correctnessRules = defineRules({
  'unicorn/no-await-in-promise-methods': 'error',
  'unicorn/no-empty-file': 'warn',
  'unicorn/no-invalid-fetch-options': 'off',
  'unicorn/no-invalid-remove-event-listener': 'off',
  'unicorn/no-new-array': 'error',
  'unicorn/no-single-promise-in-promise-methods': 'off',
  'unicorn/no-thenable': 'warn',
  'unicorn/no-unnecessary-await': 'error',
  'unicorn/no-useless-fallback-in-spread': 'error',
  'unicorn/no-useless-length-check': 'error',
  'unicorn/no-useless-spread': 'off',
  'unicorn/prefer-set-size': 'error',
  'unicorn/prefer-string-starts-ends-with': 'error',
})

const pedanticRules = defineRules({
  'unicorn/consistent-assert': 'off',
  'unicorn/consistent-empty-array-spread': 'error',
  'unicorn/escape-case': 'error',
  'unicorn/explicit-length-check': 'off',
  'unicorn/new-for-builtins': 'error',
  'unicorn/no-array-callback-reference': 'off',
  'unicorn/no-hex-escape': 'off',
  'unicorn/no-immediate-mutation': 'off',
  'unicorn/no-instanceof-array': 'error',
  'unicorn/no-lonely-if': 'off',
  'unicorn/no-negated-condition': 'off',
  'unicorn/no-negation-in-equality-check': 'error',
  'unicorn/no-new-buffer': 'error',
  'unicorn/no-object-as-default-parameter': 'off',
  'unicorn/no-static-only-class': 'off',
  'unicorn/no-this-assignment': 'off',
  'unicorn/no-typeof-undefined': 'off',
  'unicorn/no-unnecessary-array-flat-depth': 'off',
  'unicorn/no-unnecessary-array-splice-count': 'off',
  'unicorn/no-unnecessary-slice-end': 'off',
  'unicorn/no-unreadable-iife': 'off',
  'unicorn/no-useless-promise-resolve-reject': 'error',
  'unicorn/no-useless-switch-case': 'error',
  'unicorn/no-useless-undefined': 'off',
  'unicorn/prefer-array-flat': 'off',
  'unicorn/prefer-array-some': 'off',
  'unicorn/prefer-at': 'off',
  'unicorn/prefer-blob-reading-methods': 'off',
  'unicorn/prefer-code-point': 'off',
  'unicorn/prefer-date-now': 'off',
  'unicorn/prefer-dom-node-append': 'off',
  'unicorn/prefer-dom-node-dataset': 'off',
  'unicorn/prefer-dom-node-remove': 'off',
  'unicorn/prefer-event-target': 'off',
  'unicorn/prefer-import-meta-properties': 'off',
  'unicorn/prefer-math-min-max': 'off',
  'unicorn/prefer-math-trunc': 'off',
  'unicorn/prefer-native-coercion-functions': 'off',
  'unicorn/prefer-number-coercion': 'off',
  'unicorn/prefer-prototype-methods': 'off',
  'unicorn/prefer-query-selector': 'off',
  'unicorn/prefer-regexp-test': 'off',
  'unicorn/prefer-single-call': 'off',
  'unicorn/prefer-string-replace-all': 'off',
  'unicorn/prefer-string-slice': 'off',
  'unicorn/prefer-top-level-await': 'off',
  'unicorn/prefer-type-error': 'error',
  'unicorn/require-number-to-fixed-digits-argument': 'off',
})

const perfRules = defineRules({
  'unicorn/prefer-array-find': 'off',
  'unicorn/prefer-array-flat-map': 'off',
  'unicorn/prefer-set-has': 'off',
})

const restrictionRules = defineRules({
  'unicorn/import-style': 'off',
  'unicorn/no-abusive-eslint-disable': 'off',
  'unicorn/no-anonymous-default-export': 'off',
  'unicorn/no-array-for-each': 'off',
  'unicorn/no-array-reduce': ['error', { allowSimpleOperations: true }],
  'unicorn/no-document-cookie': 'off',
  'unicorn/no-length-as-slice-end': 'off',
  'unicorn/no-magic-array-flat-depth': 'off',
  'unicorn/no-process-exit': 'off',
  'unicorn/no-useless-error-capture-stack-trace': 'off',
  'unicorn/prefer-modern-math-apis': 'off',
  'unicorn/prefer-module': 'off',
  'unicorn/prefer-node-protocol': 'error',
  'unicorn/prefer-number-properties': 'error',
})

const styleRules = defineRules({
  'unicorn/catch-error-name': 'off',
  'unicorn/consistent-date-clone': 'off',
  'unicorn/consistent-existence-index-check': 'off',
  'unicorn/consistent-template-literal-escape': 'off',
  'unicorn/custom-error-definition': 'off',
  'unicorn/empty-brace-spaces': 'off',
  'unicorn/error-message': 'error',
  'unicorn/explicit-timer-delay': 'off',
  'unicorn/filename-case': 'off',
  'unicorn/max-nested-calls': 'off',
  'unicorn/no-array-method-this-argument': 'off',
  'unicorn/no-await-expression-member': 'off',
  'unicorn/no-console-spaces': 'off',
  'unicorn/no-nested-ternary': 'off',
  'unicorn/no-null': 'off',
  'unicorn/no-unreadable-array-destructuring': 'off',
  'unicorn/no-useless-collection-argument': 'off',
  'unicorn/no-zero-fractions': 'off',
  'unicorn/number-literal-case': 'error',
  'unicorn/numeric-separators-style': 'off',
  'unicorn/prefer-array-index-of': 'off',
  'unicorn/prefer-bigint-literals': 'off',
  'unicorn/prefer-class-fields': 'off',
  'unicorn/prefer-classlist-toggle': 'off',
  'unicorn/prefer-default-parameters': 'off',
  'unicorn/prefer-dom-node-text-content': 'error',
  'unicorn/prefer-export-from': 'off',
  'unicorn/prefer-global-this': 'off',
  'unicorn/prefer-includes': 'error',
  'unicorn/prefer-keyboard-event-key': 'off',
  'unicorn/prefer-logical-operator-over-ternary': 'off',
  'unicorn/prefer-modern-dom-apis': 'off',
  'unicorn/prefer-negative-index': 'off',
  'unicorn/prefer-object-from-entries': 'off',
  'unicorn/prefer-optional-catch-binding': 'off',
  'unicorn/prefer-reflect-apply': 'off',
  'unicorn/prefer-response-static-json': 'off',
  'unicorn/prefer-spread': 'off',
  'unicorn/prefer-string-raw': 'off',
  'unicorn/prefer-string-trim-start-end': 'off',
  'unicorn/prefer-structured-clone': 'off',
  'unicorn/prefer-ternary': 'off',
  'unicorn/relative-url-style': 'off',
  'unicorn/require-array-join-separator': 'off',
  'unicorn/require-module-attributes': 'off',
  'unicorn/switch-case-braces': 'off',
  'unicorn/switch-case-break-position': 'off',
  'unicorn/text-encoding-identifier-case': 'off',
  'unicorn/throw-new-error': 'error',
})

const suspiciousRules = defineRules({
  'unicorn/consistent-function-scoping': 'error',
  'unicorn/no-accessor-recursion': 'off',
  'unicorn/no-array-fill-with-reference-type': 'off',
  'unicorn/no-array-reverse': 'off',
  'unicorn/no-array-sort': 'off',
  'unicorn/no-confusing-array-with': 'off',
  'unicorn/no-instanceof-builtins': 'error',
  'unicorn/prefer-add-event-listener': 'off',
  'unicorn/require-module-specifiers': 'off',
  'unicorn/require-post-message-target-origin': 'error',
})

const nurseryRules = defineRules({
  'unicorn/no-useless-iterator-to-array': 'off',
})

export function unicorn({ rules }: UnicornOptions = {}): OxlintConfig {
  return {
    plugins: ['unicorn'],
    rules: {
      ...correctnessRules,
      ...pedanticRules,
      ...perfRules,
      ...restrictionRules,
      ...styleRules,
      ...suspiciousRules,
      ...nurseryRules,
      ...rules,
    },
  }
}
